version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
   
    volumes:
      - "./frontend:/app"  
      - "/app/node_modules"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
     
       URI: mongodb://nesrine:nesrine@db:27017

    volumes:
      - "./backend:/app"  
      
    networks:
      - app-network
    
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nesrine
      MONGO_INITDB_ROOT_PASSWORD: nesrine
    volumes:
      - db-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: